version: 2.1
jobs:
  step-one:
    docker:
      - image: circleci/node:12.18.2-browsers
    working_directory: ~/carbon-angular-tutorial/carbon-angular-tutorial
    steps:
      - checkout
      - run: pwd
      - run: ls -lR
      - run: pwd
      - run: ls -lR
      - run: npm install
      - run: npm run test:once
      - run: npm run build

workflows:
    main:
      jobs:
        - step-one
