version: 2.1

jobs:
  step-one:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          CHROME_BIN: /usr/bin/firefox

    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:once
      - run: npm run build
      
workflows:
    main:
      jobs:
        - step-one