version: 2.1

jobs:
  step-one:
    docker:
      - image: cimg/node:14.19.3
      environment:
                CHROME_BIN: "/usr/bin/google-chrome"
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:once
      - run: npm run build
      
workflows:
    main:
      jobs:
        - step-one
