version: 2.1

jobs:
  step-one:
    docker:
      - image: cimg/node:14.19.3

    working_directory: ~/repo
    steps:
      - checkout
      - browser-tools/install-chrome
      - run: npm install
      - run: npm run test:once
      - run: npm run build
      - run:
          name: Run TestCafe tests on headless Chrome
          command: npm run test:chrome:headless
      
workflows:
    main:
      jobs:
        - step-one
