version: 2.1
jobs:
  step-one:
    docker:
      - image: circleci/node:12.18.2-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: pwd
      - run: ls -lR
      - run: ls -lR | more
      - run: cd carbon-angular-tutorial
      - run: pwd
      - run: ls -lR
      - run: npm install
      - run: npm run test:once
      - run: npm run build

workflows:
    main:
      jobs:
        - step-one
