version: 2.1
jobs:
  step-one:
    docker:
      - image: circleci/node:12.18.2-browsers
    working_directory: ~/repo/carbon-angular-tutorial
    steps:
      - checkout:
        path: ~/repo
      - run: npm install
      - run: npm run test:once
      - run: npm run build

workflows:
    main:
      jobs:
        - step-one
