version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  step-one:
    docker:
      - image: circleci/node:12.18.2-browsers
      - image: cimg/node:16.17.0-browsers
    working_directory: ~/repo
    steps:
      - browser-tools/install-chrome
      - checkout
      - run: npm install
      - run: npm run test:once

workflows:
    main:
      jobs:
        - step-one
