version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  step-one:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run test:once
workflows:
    build-and-test:
      jobs:
        - step-one
