version: 2.1
jobs:
  step-five:
    docker:
      - image: circleci/node:16.13.1-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:once
      - run: npm run build

workflows:
    main:
      jobs:
        - step-five
