version: 2.1

orbs:
  node:
  version: 14
  
jobs:
  step-one:
    docker:
      - image: circleci/node:12.18.2-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test:once
      - run: npm run build

workflows:
    main:
      jobs:
        - step-one
